# Generated by Django 3.0.5 on 2020-04-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200429_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
