# Generated by Django 3.0.5 on 2020-04-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200429_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='streak_percentile',
            field=models.IntegerField(default=1),
        ),
    ]
